---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

phone_data <- read_csv("data/20190928-items.csv")

library(janitor)
```
```{r}
phone_data <- clean_names(phone_data)

head(phone_data)

view(phone_data)
```

Find the brand with the highest number of phones in the data set 

```{r}
phone_data %>%
  distinct(brand)

phone_data %>%
  group_by(brand) %>%
  summarise(no_phones = n()) %>%
  arrange(desc(no_phones)) %>%
  top_n(1)
```
For your top brand, plot the distribution of phone ratings as a probability density, overlaying a fitted normal distribution. Do you think the normal distribution provides a good model of these ratings?

```{r}
 samsung_rating_stats <- phone_data %>%
  filter(brand == "Samsung") %>% 
   summarise(
     num = n(), 
     mean_rating = mean(rating), 
     sd = sd(rating))

phone_data %>%
  filter(brand == "Samsung") %>%
  ggplot() + 
    aes(x = rating) + 
    geom_histogram(aes(y = ..density..), col = "white") + 
    stat_function(
     fun = dnorm, 
      args = list(
      mean = samsung_rating_stats$mean_rating, 
      sd = samsung_rating_stats$sd), 
      col = "red"
  )

  
  
```

```{r}

samsung_rating_stats$mean_rating

phone_data %>% 
  filter(brand == "Samsung") %>%
  filter(rating >= samsung_rating_stats$mean_rating - samsung_rating_stats$sd) %>%
  filter(rating <= samsung_rating_stats$mean_rating + samsung_rating_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))


```

```{r}
phone_data %>% 
  filter(brand == "Samsung") %>%
  filter(rating >= samsung_rating_stats$mean_rating - 2*(samsung_rating_stats$sd)) %>%
  filter(rating <= samsung_rating_stats$mean_rating + 2*(samsung_rating_stats$sd)) %>%
  summarise(prop_within_2sd = n() / nrow(samsung_ratings))
```

```{r}
phone_data %>% 
  filter(brand == "Samsung") %>%
  filter(rating >= samsung_rating_stats$mean_rating - 3 * samsung_rating_stats$sd) %>%
  filter(rating <= samsung_rating_stats$mean_rating + 3 * samsung_rating_stats$sd) %>%
  summarise(prop_within_3sd = n() / nrow(samsung_ratings))
```
```{r}
qqnorm(samsung_ratings$rating)
qqline(samsung_ratings$rating)

```


