---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(infer)
library(janitor)
```

```{r}
ames <- read_csv("data/ames.csv")

ames <- clean_names(ames)
```




```{r}
glimpse(ames)
```


Investigate the distribution of lot_area

Is is normal?

```{r}
ames %>% 
  ggplot + 
  aes(x = lot_area) + 
  geom_histogram(colour = "black", bins = 1000)
```


```{r}
ames %>% 
  summarise(
    mean_lot_area = mean(lot_area))



```




```{r}

#three part infer workflow: specify, generate, calculate -- and pipe to visualise

bootstrap_sample_1000 <- ames %>%
  specify(response = lot_area) %>% 
  generate(reps = 10000, type =  "bootstrap") %>%
  calculate(stat = "mean") 

bootstrap_sample_1000 %>%
  visualise(bins = 30)


```


```{r}
bootstrap_lot_area_ci <- bootstrap_sample_1000 %>%
  get_confidence_interval(level = 0.95, type = "percentile")

bootstrap_lot_area_ci

bootstrap_sample_1000 %>%
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = bootstrap_lot_area_ci)
```



```{r}
bootstrap_lot_area_ci_99 <- bootstrap_sample_1000 %>%
  get_confidence_interval(level = 0.99, type = "percentile")


bootstrap_lot_area_ci

bootstrap_lot_area_ci_99


#as expected, the range of the 99% confidence interval is larger 

```



```{r}
point_est_mean_plot <- bootstrap_sample_1000 %>% 
  summarise(mean(stat))

point_est_mean_plot
```

Calculate a point estimate and 95% CI for the proportion of houses in the data built before 1920. Does the number of reps you use matter? [Investigate reps from 200 up to 50000, memory of your laptop permitting].



```{r}

glimpse(ames)

ames_prior_1920 <- ames %>%
  filter(year_built <= 1920)

ames <- ames %>% 
  mutate(early_build = as.numeric(year_built <= 1920))

ames %>% 
  filter(early_build == 1)


```

```{r}

#for reps = 200

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 200, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)

```

```{r}
#for reps = 500

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 500, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```

```{r}
#for reps = 1000

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```


```{r}
#for reps = 1500

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 1500, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```

```{r}
#for reps = 2000

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 2000, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```

```{r}
#for reps = 200

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 10000, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```


```{r}
#for reps = 30000

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 30000, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)
```

```{r}
#for reps = 50000

bootstrap_early_build <- ames %>% 
  specify(response = early_build) %>% 
  generate(reps = 50000, type = "bootstrap") %>% 
  calculate(stat = "mean")

early_build_ci_95 <- bootstrap_early_build %>% 
  get_ci(level = 0.95, type = "percentile")

bootstrap_early_build %>% 
  visualise(bins = 30) + 
  shade_confidence_interval(endpoints = early_build_ci_95)

# the distribution stabilises to become more normal above 20000 reps or near 
```

